#- name: 'change default user passwod'
#  shell: 'echo "pi:unsecure" | chpasswd'

- name: 'install prerequisites'
  package:
    name: "{{item}}"
    state: latest
  with_items:
  - vim
  - lm-sensors
  become: yes
